/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.corretoraImovel.view;

import br.com.corretoraImovel.controlle.AgendamentoResource;
import br.com.corretoraImovel.model.*;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.core.Response;
import org.glassfish.jersey.client.ClientResponse;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.*;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author marco
 */
public class TelaDeAgendamentoDeVisitas extends JFrame {

    /**
     * Creates new form TelaDeAgendamentoDeVisitas
     */
    public TelaDeAgendamentoDeVisitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        jPanel1 = new JPanel();
        jPanel16 = new JPanel();
        jScrollPane9 = new JScrollPane();
        jTCV = new JTable();
        jScrollPane10 = new JScrollPane();
        jTDI = new JTable();
        jScrollPane8 = new JScrollPane();
        jTCP = new JTable();
        jLabel38 = new JLabel();
        jTextCD8 = new JTextField();
        jBB19 = new JButton();
        jBB20 = new JButton();
        jLabel39 = new JLabel();
        jLabel40 = new JLabel();
        jTextDI8 = new JTextField();
        jTextCDV8 = new JTextField();
        jBB21 = new JButton();
        jLabel42 = new JLabel();
        jLabel43 = new JLabel();
        jLabel44 = new JLabel();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        jEV = new JLabel();
        jFormattedTextCPFV = new JFormattedTextField();
        jLabel2 = new JLabel();
        jLabel1 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jTextVI = new JTextField();
        jTextEV = new JTextField();
        jTextTI = new JTextField();
        jTextB = new JTextField();
        jTextVC = new JTextField();
        jTextD = new JTextField();
        jFormattedTextHora = new JFormattedTextField();
        jSeparator1 = new JSeparator();
        jSeparator2 = new JSeparator();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        jTextEP = new JTextField();
        jLabel19 = new JLabel();
        jTextC = new JTextField();
        jTextNV = new JTextField();
        jTextNP1 = new JTextField();
        jFormattedTextCPFP = new JFormattedTextField();
        jFormattedTextData = new JFormattedTextField();
        jSeparator3 = new JSeparator();
        jLabel20 = new JLabel();
        jTextE = new JTextField();
        jFormattedTextTP = new JFormattedTextField();
        jFormattedTextTV = new JFormattedTextField();
        jBSalvar1 = new JButton();
        jLabel5 = new JLabel();
        jLabel41 = new JLabel();
        jSeparator4 = new JSeparator();
        jLabel14 = new JLabel();
        jSeparator6 = new JSeparator();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);

   //     jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);






        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Cadastro de Visitante");

        jTextCD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jBB19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBB19.setText("Buscar");
        jBB19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBB19ActionPerformed(evt);
            }
        });

        jBB20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBB20.setText("Buscar");
        jBB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBB20ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setText("Dados do Imóvel");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setText("Dados do Proprietário");

        jTextDI8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTextCDV8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextCDV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCDV8ActionPerformed(evt);
            }
        });

        jBB21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBB21.setText("Buscar");
        jBB21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBB21ActionPerformed(evt);
            }
        });

//        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel42.setText("Cadastro de Visitante");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setText("Dados do Proprietário");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setText("Dados do Imóvel");

        GroupLayout jPanel16Layout = new GroupLayout(jPanel16);
    //    jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel38))
                    .addComponent(jTextCDV8, GroupLayout.DEFAULT_SIZE, 237, GroupLayout.DEFAULT_SIZE)
                    .addComponent(jTextCDV8, GroupLayout.DEFAULT_SIZE, 50, GroupLayout.DEFAULT_SIZE)

                        .addComponent(jBB21))
                .addGap(42, 42, 42)
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCD8, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBB19))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jBB20)
                            .addComponent(jLabel39)
                            .addComponent(jTextDI8, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel42)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(302, 302, 302))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 81, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 582, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, 582, GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92))
                            .addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, 755, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel44)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(289, 289, 289)
                    .addComponent(jLabel43)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addGap(12, 12, 12)
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCD8, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCDV8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextDI8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jBB21)
                    .addComponent(jBB19)
                    .addComponent(jBB20))
                .addGap(32, 32, 32)
                .addComponent(jLabel42)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel43)
                    .addContainerGap(1541, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Telefone do Visitante");

        jEV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jEV.setText("Email do Visitante");

        try {
            jFormattedTextCPFV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextCPFV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CPF do Visitante");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nome do Visitante");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Data e Hora");

//        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
//        jLabel7.setText("Dados do Imóvel");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Nome do Proprietário");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Endereço");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Valor IPTU");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Valor Condomínio");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Taxa de Incêndio");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Dormitórios");

        jTextVI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVIActionPerformed(evt);
            }
        });

        jTextEV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextTI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextVC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVCActionPerformed(evt);
            }
        });

        jTextD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        try {
            jFormattedTextHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextHora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jFormattedTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextHoraActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("CPF do Proprietário");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Telefone do Proprietário");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setText("Dados do Proprietário");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Email do Proprietário");

        jTextEP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Complemento");

        jTextC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNVActionPerformed(evt);
            }
        });

        jTextNP1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        try {
            jFormattedTextCPFP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextCPFP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        try {
            jFormattedTextData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jFormattedTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextDataActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Bairro");

        jTextE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEActionPerformed(evt);
            }
        });

        try {
            jFormattedTextTP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextTP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        try {
            jFormattedTextTV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextTV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jBSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBSalvar1.setText("Salvar");
        jBSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jBSalvar1ActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextC, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextVI)
                                        .addComponent(jTextVC)
                                        .addComponent(jTextTI)
                                        .addComponent(jTextD, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel19)
                                    .addComponent(jTextB, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextTP, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextE, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jTextEP, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedTextCPFP, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jTextNP1, GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 717, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addGroup(GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(263, 263, 263)
                            .addComponent(jFormattedTextData, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextHora))
                        .addGroup(GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(269, 269, 269)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGap(178, 178, 178)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 301, GroupLayout.DEFAULT_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextNV, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jBSalvar1, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEV)
                    .addComponent(jTextEV)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextTV, GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jFormattedTextCPFV))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                    .addComponent(jLabel5)
                    .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNV, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextCPFV, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextTV, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEV)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEV, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextHora, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextData, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNP1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextCPFP, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextTP, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEP, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextE, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextB, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextC, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextVI, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextVC, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextTI, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextD, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBSalvar1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Cadastro de Visitante");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel41.setText("Visitas Agendadas");

        jSeparator4.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
      //  jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.DEFAULT_SIZE)
               )
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator4, GroupLayout.DEFAULT_SIZE, 1921, GroupLayout.DEFAULT_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()

                            .addGap(18, 18, 18)
                            .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.DEFAULT_SIZE)
                    ))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Projeto Imobiliária GTEC - Desenvolvido por Marco, Clemerson, Danielle, Thompson e Bhernardo - 2024");

       GroupLayout layout = new GroupLayout(getContentPane());
     //   javax.swing.JPanel layout = new javax.swing.JPanel(getContentPane().getLayout());
     //   getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jSeparator6, GroupLayout.DEFAULT_SIZE, 707, GroupLayout.DEFAULT_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1807, GroupLayout.DEFAULT_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1925, GroupLayout.DEFAULT_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, GroupLayout.DEFAULT_SIZE, 10, GroupLayout.DEFAULT_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.DEFAULT_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVCActionPerformed

    private void jTextVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVIActionPerformed

    private void jFormattedTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextHoraActionPerformed

    private void jFormattedTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextDataActionPerformed

    private void jTextNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNVActionPerformed

    private void jBSalvar1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_jBSalvar1ActionPerformed
//        DefaultHttpClient httpClient = new DefaultHttpClient();
//        HttpGet getRequest = new HttpGet(
//                "http://localhost:8080/agendamentos");
//        getRequest.addHeader("accept", "application/json");

       // HttpResponse response = httpClient.execute(getRequest);

//        if (response.getStatusLine().getStatusCode() != 200) {
//            throw new RuntimeException("Failed : HTTP error code : "
//                    + response.getStatusLine().getStatusCode());
//        }

        AgendamentoResource agendamento = new AgendamentoResource();
        Agendamento ag = new Agendamento();
        LocalDate date = LocalDate.of(2024,06, 30);
        LocalTime hora      = LocalTime.now();

        //preenchendo os objetos
       // Pessoa visitante = getVisitanteAgendamento();
       // Proprietario proprietario = getProprietarioAgendamento();

        ag.setData(date);
        ag.setHora(hora);
        imovel.setEndereco(end);
        imovel.setProprietario(pro);
        ag.setPessoa(Visitante);
        ag.setImovel(imovel);
        Response response = agendamento.save(ag);

        if (response.getStatus() == 201) {
            JOptionPane.showMessageDialog (null, "Agendamento criado com sucesso!", "Agendamento", JOptionPane.INFORMATION_MESSAGE);
        }

        System.out.println("oie btn salvar");
    }//GEN-LAST:event_jBSalvar1ActionPerformed

    //metodo para pegar os dados da tela - Pessoa

    public Pessoa getVisitanteAgendamento(){
        Pessoa pessoaVisitante = new Pessoa();

        pessoaVisitante.setNome(jTextNV.getText());
        pessoaVisitante.setDocumento(jTextNV.getText());
        pessoaVisitante.setTelefone(jTextNV.getText());
        pessoaVisitante.setEmail(jTextNV.getText());

        return pessoaVisitante;
    }

    //metodo para pegar os dados da tela - Pessoa

    public Proprietario getProprietarioAgendamento(){
        Proprietario proprietarioAgendamento = new Proprietario();

        proprietarioAgendamento.setNome(jTextNV.getText());
        proprietarioAgendamento.setDocumento(jTextNV.getText());
        proprietarioAgendamento.setTelefone(jTextNV.getText());
        proprietarioAgendamento.setEmail(jTextNV.getText());

        return proprietarioAgendamento;
    }


    private void jTextEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEActionPerformed

    private void jBB19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBB19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBB19ActionPerformed

    private void jBB20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBB20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBB20ActionPerformed

    private void jBB21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBB21ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBB21ActionPerformed

    private void jTextCDV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCDV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCDV8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Pessoa Visitante = new Pessoa("Marco", "12309880750", "2134099076", "cudeapito@gmail.com");
        System.out.println(Visitante.getNome());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeAgendamentoDeVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeAgendamentoDeVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeAgendamentoDeVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeAgendamentoDeVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeAgendamentoDeVisitas().setVisible(true);
            }
        });
    }
    Pessoa Visitante = new Pessoa("Marco", "11876880708", "2134099076", "cudeapito@gmail.com");
    Endereco end = new Endereco (10L,"Rua x","Dagua","Casa");
    Proprietario pro = new Proprietario("nome","11876880708","telefone","email");
    Imovel imovel = new Imovel(20L,end, 2, 100.00, 100.00,200.00,30.0,pro);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBB1;
    private JButton jBB10;
    private JButton jBB11;
    private JButton jBB12;
    private JButton jBB13;
    private JButton jBB14;
    private JButton jBB15;
    private JButton jBB16;
    private JButton jBB17;
    private JButton jBB18;
    private JButton jBB19;
    private JButton jBB2;
    private JButton jBB20;
    private JButton jBB21;
    private JButton jBB3;
    private JButton jBB4;
    private JButton jBB5;
    private JButton jBB6;
    private JButton jBB7;
    private JButton jBB8;
    private JButton jBB9;
    private JButton jBSalvar1;
    private JLabel jEV;
    private JFormattedTextField jFormattedTextCPFP;
    private JFormattedTextField jFormattedTextCPFV;
    private JFormattedTextField jFormattedTextData;
    private JFormattedTextField jFormattedTextHora;
    private JFormattedTextField jFormattedTextTP;
    private JFormattedTextField jFormattedTextTV;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel33;
    private JLabel jLabel34;
    private JLabel jLabel35;
    private JLabel jLabel36;
    private JLabel jLabel37;
    private JLabel jLabel38;
    private JLabel jLabel39;
    private JLabel jLabel4;
    private JLabel jLabel40;
    private JLabel jLabel41;
    private JLabel jLabel42;
    private JLabel jLabel43;
    private JLabel jLabel44;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel14;
    private JPanel jPanel16;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane10;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    private JScrollPane jScrollPane8;
    private JScrollPane jScrollPane9;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator4;
    private JSeparator jSeparator6;
    private JTable jTCP;
    private JTable jTCV;
    private JTable jTDI;
    private JTextField jTextB;
    private JTextField jTextC;
    private JTextField jTextCD2;
    private JTextField jTextCD3;
    private JTextField jTextCD4;
    private JTextField jTextCD5;
    private JTextField jTextCD6;
    private JTextField jTextCD7;
    private JTextField jTextCD8;
    private JTextField jTextCDV2;
    private JTextField jTextCDV3;
    private JTextField jTextCDV4;
    private JTextField jTextCDV5;
    private JTextField jTextCDV6;
    private JTextField jTextCDV7;
    private JTextField jTextCDV8;
    private JTextField jTextD;
    private JTextField jTextDI2;
    private JTextField jTextDI3;
    private JTextField jTextDI4;
    private JTextField jTextDI5;
    private JTextField jTextDI6;
    private JTextField jTextDI7;
    private JTextField jTextDI8;
    private JTextField jTextE;
    private JTextField jTextEP;
    private JTextField jTextEV;
    private JTextField jTextNP1;
    private JTextField jTextNV;
    private JTextField jTextTI;
    private JTextField jTextVC;
    private JTextField jTextVI;
    // End of variables declaration//GEN-END:variables
}
